version: "3.8"
services:
  postgres-db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    environment:
      POSTGRES_DB: MilkStgo
      POSTGRES_PASSWORD: Simon_789
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  app:
    container_name: project-milkstgo
    image: simonsaez/project-milkstgo
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/MilkStgo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Simon_789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db
