insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00001', 'Trix Egan', 'C', 'Si');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00002', 'Adorne Lardner', 'A', 'No');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00003', 'Dorothea Yushachkov', 'A', 'No');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00004', 'Enrico Ching', 'B', 'Si');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00005', 'Janeczka Ryding', 'A', 'No');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00006', 'Deloria Singh', 'C', 'Si');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00007', 'Lind Koomar', 'B', 'No');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00008', 'Rikki Beckers', 'A', 'Si');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00009', 'Alejandrina Sotheby', 'B', 'No');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00010', 'Maryellen Wiffen', 'C', 'Si');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00011', 'Claudia Flaune', 'D', 'Si');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00012', 'Izzy Janousek', 'C', 'Si');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00013', 'Cornie Laddle', 'C', 'Si');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00014', 'Gayler Beddoe', 'C', 'No');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00015', 'Rozele Pollington', 'D', 'No');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00016', 'Korie Behne', 'A', 'Si');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00017', 'Blythe Larderot', 'A', 'Si');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00018', 'Etti Vinson', 'D', 'Si');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00019', 'Jerry Axton', 'B', 'No');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00020', 'Deedee Grube', 'D', 'No');
insert into proveedores (proveedor_id, nombre, categoria, afecto_retencion) values ('00021', 'Lotte Adolthine', 'C', 'Si');

insert into quincenas (fecha, proveedor_id, nombre_proveedor, kls_Leche, numero_dias_leche, promedio_kls_leche, variacion_leche, grasa, variacion_grasa, solido, variacion_solido, pago_leche, pago_grasa, pago_solido, bonificacion, descuento_leche, descuento_grasa, descuento_solido, pago_total, retencion, monto_final) values ('2023/02/1', '00003', 'Dorothea Yushachkov', 720, 9, 80, 10, 50, 30, 10, 5, 720000, 86400, -93600, 0, 0, 0, 0, 712800, 0, 712800);
insert into quincenas (fecha, proveedor_id, nombre_proveedor, kls_Leche, numero_dias_leche, promedio_kls_leche, variacion_leche, grasa, variacion_grasa, solido, variacion_solido, pago_leche, pago_grasa, pago_solido, bonificacion, descuento_leche, descuento_grasa, descuento_solido, pago_total, retencion, monto_final) values ('2023/02/1', '00004', 'Enrico Ching', 720, 9, 80, 10, 50, 30, 10, 5, 720000, 86400, -93600, 0, 0, 0, 0, 712800, 0, 712800);
insert into quincenas (fecha, proveedor_id, nombre_proveedor, kls_Leche, numero_dias_leche, promedio_kls_leche, variacion_leche, grasa, variacion_grasa, solido, variacion_solido, pago_leche, pago_grasa, pago_solido, bonificacion, descuento_leche, descuento_grasa, descuento_solido, pago_total, retencion, monto_final) values ('2023/02/1', '00005', 'Janeczka Ryding', 720, 9, 80, 10, 50, 30, 10, 5, 720000, 86400, -93600, 0, 0, 0, 0, 712800, 0, 712800);
insert into quincenas (fecha, proveedor_id, nombre_proveedor, kls_Leche, numero_dias_leche, promedio_kls_leche, variacion_leche, grasa, variacion_grasa, solido, variacion_solido, pago_leche, pago_grasa, pago_solido, bonificacion, descuento_leche, descuento_grasa, descuento_solido, pago_total, retencion, monto_final) values ('2023/02/1', '00006', 'Deloria Singh', 720, 9, 80, 10, 50, 30, 10, 5, 720000, 86400, -93600, 0, 0, 0, 0, 712800, 0, 712800);